#!/usr/bin/python3
"""Module that factorizes as many numbers as possible
into a product of two smaller numbers."""
import sys


def factorize(value):
    """Prints a simple decomposition of an integer > 1"""
    if value < 2:
        return

    i = 2
    while value % i:
        i += 1

    print()
    print(f"{value} <- value-bef")
    print("{:.0f} = {:.0f} * {:.0f}".format(value, value / i, i))
    print(f"{value} <- value-aft")
    print()


if len(sys.argv) != 2:
    sys.exit()

try:
    with open(sys.argv[1]) as file:
        for line in file:
            value = int(line.rstrip())
            factorize(value)
except FileNotFoundError:
    pass

